set_property PACKAGE_PIN P4 [get_ports {p1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p1[0]}]

set_property PACKAGE_PIN P5 [get_ports {p1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p1[1]}]

set_property PACKAGE_PIN R1 [get_ports {p2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p2[0]}]

set_property PACKAGE_PIN N4 [get_ports {p2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {p2[1]}]


set_property PACKAGE_PIN F6 [get_ports {o1}]
set_property IOSTANDARD LVCMOS33 [get_ports {o1}]

set_property PACKAGE_PIN G4 [get_ports {o2}]
set_property IOSTANDARD LVCMOS33 [get_ports {o2}]

set_property PACKAGE_PIN G3 [get_ports {o3}]
set_property IOSTANDARD LVCMOS33 [get_ports {o3}]

set_property PACKAGE_PIN B4 [get_ports {tub_control1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[7]}]
set_property PACKAGE_PIN A4 [get_ports {tub_control1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[6]}]
set_property PACKAGE_PIN A3 [get_ports {tub_control1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[5]}]
set_property PACKAGE_PIN B1 [get_ports {tub_control1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[4]}]
set_property PACKAGE_PIN A1 [get_ports {tub_control1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[3]}]
set_property PACKAGE_PIN B3 [get_ports {tub_control1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[2]}]
set_property PACKAGE_PIN B2 [get_ports {tub_control1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[1]}]
set_property PACKAGE_PIN D5 [get_ports {tub_control1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control1[0]}]

set_property PACKAGE_PIN D4 [get_ports {tub_control2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[7]}]
set_property PACKAGE_PIN E3 [get_ports {tub_control2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[6]}]
set_property PACKAGE_PIN D3 [get_ports {tub_control2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[5]}]
set_property PACKAGE_PIN F4 [get_ports {tub_control2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[4]}]
set_property PACKAGE_PIN F3 [get_ports {tub_control2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[3]}]
set_property PACKAGE_PIN E2 [get_ports {tub_control2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[2]}]
set_property PACKAGE_PIN D2 [get_ports {tub_control2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[1]}]
set_property PACKAGE_PIN H2 [get_ports {tub_control2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control2[0]}]

set_property PACKAGE_PIN G2 [get_ports {tub_sel1}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_sel1}]
set_property PACKAGE_PIN G6 [get_ports {tub_sel2}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_sel2}]